# Generated by Django 3.2.4 on 2023-04-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='start_time',
        ),
    ]
