# Generated by Django 3.2.4 on 2023-04-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_session_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='sessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=8)),
                ('user', models.CharField(max_length=60)),
                ('mr', models.CharField(max_length=60)),
                ('ear', models.CharField(max_length=60)),
                ('time_ms', models.CharField(max_length=60)),
            ],
        ),
    ]
