# Generated by Django 3.2.4 on 2023-05-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_sessionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='session_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=8)),
                ('user', models.CharField(max_length=60)),
                ('permission', models.CharField(max_length=60)),
            ],
        ),
    ]
