# Generated by Django 3.2.4 on 2023-05-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_session_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_members',
            name='user_id',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
